# Generated by Django 2.2.1 on 2019-05-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0004_validcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='money',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
